<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="42" started-at="2018-03-20T17:24:59Z" finished-at="2018-03-20T17:24:59Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="42" started-at="2018-03-20T17:24:59Z" finished-at="2018-03-20T17:24:59Z">
      <class name="companyName.testScripts.login.TestLogin">
        <test-method status="FAIL" signature="setUp()[pri:0, instance:companyName.testScripts.login.TestLogin@1faf8f2]" name="setUp" is-config="true" duration-ms="0" started-at="2018-03-20T22:54:59Z" finished-at="2018-03-20T22:54:59Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at companyName.utils.utils.selectBrowser(utils.java:23)
	at companyName.testBase.TestBase.inti(TestBase.java:35)
	at companyName.testScripts.login.TestLogin.setUp(TestLogin.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:616)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="applanch()[pri:0, instance:companyName.testScripts.login.TestLogin@1faf8f2]" name="applanch" duration-ms="1" started-at="2018-03-20T22:54:59Z" finished-at="2018-03-20T22:54:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applanch -->
        <test-method status="SKIP" signature="clsApp()[pri:0, instance:companyName.testScripts.login.TestLogin@1faf8f2]" name="clsApp" is-config="true" duration-ms="0" started-at="2018-03-20T22:54:59Z" finished-at="2018-03-20T22:54:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clsApp -->
      </class> <!-- companyName.testScripts.login.TestLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
